# Generated by Django 4.0.6 on 2022-10-18 23:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_remove_comment_user_alter_bid_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='User',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bid',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 18, 23, 33, 6, 176140)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 18, 23, 33, 6, 176140)),
        ),
    ]
