# Generated by Django 4.0.6 on 2022-10-20 17:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_bid_date_alter_comment_user_alter_listing_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='active',
        ),
        migrations.AddField(
            model_name='bid',
            name='win',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bid',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 20, 17, 31, 55, 446152)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 20, 17, 31, 55, 446152)),
        ),
    ]
